# my global config
global:
  scrape_interval:     15s # Global acquisition interval, default 1 m, set to 15s
  evaluation_interval: 15s # Global rule trigger interval, default 1 m, set 15s here

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'postgres_exporters'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'db:9187'
        labels:
          cluster: 'postgres_cluster'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '${1}:9187'
